import * as cheerio from "cheerio";
import type { CheerioAPI } from "cheerio";

export interface SerpOrganicResult {
  position: number;
  title: string;
  url: string;
  snippet: string;
}

export interface SerpAiOverview {
  text: string;
  sources: Array<{ domain: string; url: string }>;
}

export interface SerpPaaItem {
  question: string;
  answer: string;
}

export interface SerpResult {
  organic: SerpOrganicResult[];
  ai_overview: SerpAiOverview | null;
  people_also_ask: SerpPaaItem[];
  query: string;
}

export interface ParseSerpOptions {
  query: string;
  maxResults: number;
}

export function parseSerp(html: string, opts: ParseSerpOptions): SerpResult {
  const $ = cheerio.load(html);
  return {
    organic: extractOrganic($, opts.maxResults),
    ai_overview: extractAiOverview($),
    people_also_ask: extractPaa($, opts.query),
    query: opts.query,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function domainOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

// Boilerplate strings Google injects into every AI Overview wrapper. If what's
// left after stripping these is short (< 60 chars) we treat it as "no AIO".
const BOILERPLATE_PATTERNS: RegExp[] = [
  /AI can make mistakes,?\s*so double-?check responses?\.?/gi,
  /An error has occurred\.?\s*Please try again later\.?/gi,
  /An AI Overview is not available for this search\.?/gi,
  /Can'?t generate an AI overview right now\.?\s*Try again later\.?/gi,
  /Show more/gi,
  /Show less/gi,
  /Related Links/gi,
  /Generated by [A-Za-z\s]+/gi,
  /\+\d+/g, // "+6" source-count badges
  /&nbsp;/g,
];

function cleanAioText(raw: string): string {
  let out = raw;
  for (const re of BOILERPLATE_PATTERNS) out = out.replace(re, "");
  return out.replace(/\s+/g, " ").trim();
}

// Negative templates Google injects when the AIO failed/was unavailable.
// If we see only these strings inside the AIO block, treat it as missing.
const AIO_FAILURE_PATTERNS: RegExp[] = [
  /An AI Overview is not available for this search/i,
  /Can'?t generate an AI overview right now/i,
  /An error has occurred\.?\s*Please try again later/i,
];

// ---------------------------------------------------------------------------
// AI Overview
// ---------------------------------------------------------------------------

function extractAiOverview($: CheerioAPI): SerpAiOverview | null {
  // Selector strategy: try current Google markup first, then older ones.
  // Google rotates these — keep the list ordered by recency.
  const candidateSelectors = [
    ".pOOWX", // current (2026) AIO answer container
    '[data-attrid="SrpGenSumSummary"]', // older AIO wrapper
  ];
  let block = $("").first();
  for (const sel of candidateSelectors) {
    const found = $(sel).first();
    if (found.length) {
      block = found;
      break;
    }
  }
  if (!block.length) return null;

  const clone = block.clone();
  clone.find("script, style, noscript, svg, img").remove();
  clone.find('[style*="display:none"], [style*="display: none"]').remove();
  // Strip HTML comments — Google embeds JSON metadata as <!-- ... -->
  // which cheerio's .text() ignores anyway, but be explicit.
  clone.contents().each((_i, el) => {
    if (el.type === "comment") $(el).remove();
  });

  const rawText = clone.text();
  // If the only content is one of the failure templates, return null.
  if (AIO_FAILURE_PATTERNS.some((re) => re.test(rawText))) {
    const cleanedFailure = cleanAioText(rawText);
    if (cleanedFailure.length < 200) return null;
  }
  const cleaned = cleanAioText(rawText);
  if (cleaned.length < 60) return null;

  // Sources — collect external links inside the AIO block.
  const seen = new Set<string>();
  const sources: Array<{ domain: string; url: string }> = [];
  clone.find("a[href]").each((_i, el) => {
    const href = $(el).attr("href") ?? "";
    const target = href.startsWith("/url?")
      ? (new URLSearchParams(href.slice(5)).get("url") ?? "")
      : href;
    if (!/^https?:\/\//.test(target)) return;
    const d = domainOf(target);
    if (!d) return;
    if (d.endsWith("google.com") || d.endsWith("googleusercontent.com")) return;
    if (seen.has(d)) return;
    seen.add(d);
    sources.push({ domain: d, url: target });
    if (sources.length >= 10) return false;
  });

  // Fallback: extract source domains from the text itself when there are no
  // <a> tags inside the AIO container. Google often shows them as
  // "Britannica +4" / "Wikipedia +4" inline name labels, with the real URL
  // hidden inside an encrypted-tbn favicon attribute.
  if (sources.length === 0) {
    const html = clone.html() ?? "";
    const re = /url\\u003dhttps:\/\/(?:www\.)?([a-z0-9.-]+\.[a-z]{2,})/gi;
    const seenFb = new Set<string>();
    let m: RegExpExecArray | null;
    while ((m = re.exec(html)) !== null) {
      const captured = m[1];
      if (!captured) continue;
      const d = captured.replace(/^www\./, "");
      if (d.endsWith("google.com") || d.endsWith("gstatic.com")) continue;
      if (seenFb.has(d)) continue;
      seenFb.add(d);
      // Spec requires url; synthesise from the domain for fallback sources.
      sources.push({ domain: d, url: `https://${d}` });
      if (sources.length >= 8) break;
    }
  }

  return {
    text: cleaned,
    sources,
  };
}

// ---------------------------------------------------------------------------
// People Also Ask
// ---------------------------------------------------------------------------

function extractPaa($: CheerioAPI, searchQuery: string): SerpPaaItem[] {
  const out: SerpPaaItem[] = [];
  const seen = new Set<string>();
  const searchLc = searchQuery.toLowerCase().trim();

  $(".related-question-pair").each((_i, el) => {
    const q = $(el).attr("data-q");
    if (!q) return;
    const trimmed = q.trim();
    if (!trimmed) return;
    // Skip the user's own search query if Google echoes it as a "related"
    if (trimmed.toLowerCase() === searchLc) return;
    if (seen.has(trimmed.toLowerCase())) return;
    seen.add(trimmed.toLowerCase());

    // Answer container: Google reuses the AIO `pOOWX` class for the
    // expanded answer inside each PAA item.
    const $el = $(el);
    const answerBlock = $el.find(".pOOWX").first();
    let answer = "";
    if (answerBlock.length) {
      const clone = answerBlock.clone();
      clone.find("script, style, noscript, svg, img").remove();
      clone
        .find('[style*="display:none"], [style*="display: none"]')
        .remove();
      clone.contents().each((_j, c) => {
        if (c.type === "comment") $(c).remove();
      });
      const raw = clone.text();
      const cleaned = cleanAioText(raw);
      // Skip when only failure templates remain
      const onlyFailureChrome =
        AIO_FAILURE_PATTERNS.some((re) => re.test(raw)) && cleaned.length < 200;
      if (!onlyFailureChrome && cleaned.length >= 30) {
        answer = cleaned;
      }
    }
    out.push({ question: trimmed, answer });
  });
  return out;
}

// ---------------------------------------------------------------------------
// Organic results
// ---------------------------------------------------------------------------

function extractOrganic(
  $: CheerioAPI,
  maxResults: number,
): SerpOrganicResult[] {
  const out: SerpOrganicResult[] = [];
  $(".yuRUbf").each((i, el) => {
    const $el = $(el);
    const a = $el.find("a[href]").first();
    const href = a.attr("href") ?? "";
    if (!href.startsWith("http")) return;
    const title = $el.find("h3").first().text().trim();
    if (!title) return;
    // Snippet usually lives in the parent or a sibling .VwiC3b
    const $parent = $el.parent();
    const snippetEl = $parent.find(".VwiC3b").first().length
      ? $parent.find(".VwiC3b").first()
      : $el.parents().slice(0, 4).find(".VwiC3b").first();
    const snippet = snippetEl.text().trim();
    out.push({
      position: i + 1,
      title,
      url: href,
      snippet,
    });
  });
  // Re-number positions after slicing so they remain 1-based and sequential
  // even when maxResults < collected count.
  return out.slice(0, maxResults).map((r, i) => ({ ...r, position: i + 1 }));
}
